version: "3.8"

services:
  kong:
    image: kong:3.4
    ports:
      - "8000:8000"     # Public API
      - "8001:8001"     # Admin API
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    networks:
      - artisthub-net

  auth-service:
    build: ./auth-service
    image: artisthub/auth-service
    networks:
      - artisthub-net

  business-logic-service:
    build: ./business-logic-service
    image: artisthub/business-logic
    networks:
      - artisthub-net

  upload-service:
    build: ./upload-service
    image: artisthub/upload-service
    networks:
      - artisthub-net

  topics-service:
    build: ./topics-service
    image: artisthub/topics-service
    networks:
      - artisthub-net

  display-service:
    build: ./display-service
    image: artisthub/display-service
    networks:
      - artisthub-net

  frontend:
    build: ./frontend
    image: artisthub/frontend
    ports:
      - "3000:80"
    depends_on:
      - kong
    networks:
      - artisthub-net

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: artisthub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - artisthub-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - artisthub-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - artisthub-net

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - artisthub-net

volumes:
  postgres-data:
  grafana-data:
  portainer-data:

networks:
  artisthub-net:
    driver: overlay
    attachable: true
