version: "3.8"

services:
  postgres-db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: mobylab-app
      POSTGRES_DB: mobylab-app
      POSTGRES_PASSWORD: mobylab-app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network
    deploy:
      placement:
        constraints: [node.role == worker]

  backend:
    image: art-community-platform-backend:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=mobylab-app;Username=mobylab-app;Password=mobylab-app
    networks:
      - backend-network
    deploy:
      placement:
        constraints: [node.role == worker]

  frontend:
    image: art-community-platform-frontend:latest
    ports:
      - "3000:80"
    networks:
      - frontend-network
    deploy:
      placement:
        constraints: [node.role == worker]

  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    networks:
      - kong-network
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.role == manager]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - monitor-network
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:

networks:
  backend-network:
  frontend-network:
  kong-network:
  monitor-network:
