version: "3.8"

services:
  kong:
    image: kong:3.4
    ports:
      - "8000:8000"     # Public API
      - "8001:8001"     # Admin API
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    networks:
      - artisthub-net

  micro-auth:
    image: cojo64/micro-auth:latest
    ports:
      - 1923:5001
    hostname: micro-auth
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres-db:5432/artisthub
    depends_on:
      - postgres-db
    networks:
      - artisthub-net

  micro-media:
    image: cojo64/micro-media:latest
    ports:
      - 1947:5001
    hostname: micro-media
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres-db:5432/artisthub
    depends_on:
      - postgres-db
    networks:
      - artisthub-net

  micro-ref:
    image: cojo64/micro-ref:latest
    ports:
      - 1948:5001
    hostname: micro-ref
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres-db:5432/artisthub
    depends_on:
      - postgres-db
    networks:
      - artisthub-net

  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: artisthub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - artisthub-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - artisthub-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - artisthub-net

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - artisthub-net

volumes:
  postgres-data:
  grafana-data:
  portainer-data:

networks:
  artisthub-net:
    # driver: overlay
    driver: bridge
