apiVersion: 1
datasources:
  - name: Postgres
    uid: Postgres
    type: postgres
    url: postgres-db:5432
    database: artisthub
    user: admin
    jsonData:
      sslmode: disable         
    secureJsonData:
      password: admin123
    isDefault: true

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
