apiVersion: 1
datasources:
  - name: Postgres
    uid: Postgres
    type: postgres
    url: mobylab-app-db:5432
    database: mobylab-app
    user: mobylab-app
    jsonData:
      sslmode: disable         
    secureJsonData:
      password: mobylab-app
    isDefault: true

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
