global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['kong-1:8001']

  - job_name: 'node resources'
    static_configs:
      - targets: ['micro-media:5001', 'micro-auth:5001', 'micro-ref:5001']
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - netstat
