name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run-compose:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./art-community-platform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker Stack services
        run: docker stack deploy -c docker-stack.yml artisthub

      - name: Show Docker logs on failure
        if: failure()
        run: docker compose logs # Will use the job's default working-directory

      - name: Stop and remove Docker Compose services
        if: always()
        run: docker compose down -v --remove-orphans # Will use the job's default working-directory
